# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Basic configuration
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: src/
    -   id: end-of-file-fixer
        files: src/
    -   id: check-yaml
    -   id: check-added-large-files

# Black
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        files: src/
        language: python
        types: [python]

# flake8
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 --max-line-length 119
        files: src/
        language: python
        types: [python]
